# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Website & Mobile starter project

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: AWS::Serverless-2016-10-31

Parameters:
  AppId:
    Type: String

Globals:
  Api:
    Auth:
      DefaultAuthorizer: MyCognitoAuthorizer
      Authorizers:
        MyCognitoAuthorizer:
          UserPoolArn: "arn:aws:cognito-idp:ap-northeast-2:953093100803:userpool/ap-northeast-2_mnvGuF0mR"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
    Domain:
      DomainName: api.rattiel.net
      CertificateArn: arn:aws:acm:ap-northeast-2:953093100803:certificate/434bc71f-f236-4057-aeae-f2f690d5817f
      EndpointConfiguration: EDGE
      Route53:
        HostedZoneId: Z04384092A2AV75XTZM4I

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  EchoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/echo.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 60
      Events:
        Api:
          Type: Api
          Properties:
            Path: /echo
            Method: GET
            Auth:
              Authorizer: MyCognitoAuthorizer
